// Master list of all Police Stations (Thana) in Bangladesh
// Structure: Division → District → Thana

export interface ThanaData {
  [division: string]: {
    [district: string]: string[]
  }
}

export const bangladeshThanas: ThanaData = {
  "Dhaka Division": {
    "Dhaka Metropolitan": [
      "Adabor",
      "Agargaon",
      "Airport",
      "Badda",
      "Banani",
      "Bangshal",
      "Cantonment",
      "Chakbazar",
      "Dakshin Khan",
      "Darus Salam",
      "Demra",
      "Dhanmondi",
      "Uttara East",
      "Uttara West",
      "Gandaria",
      "Gulshan",
      "Hatirjheel",
      "Hazaribagh",
      "Jatrabari",
      "Kadamtali",
      "Kafrul",
      "Kalabagan",
      "Kamrangirchar",
      "Khilgaon",
      "Khilkhet",
      "Kotwali",
      "Lalbagh",
      "Mirpur",
      "Mohammadpur",
      "Motijheel",
      "Mugda",
      "New Market",
      "Pallabi",
      "Paltan",
      "Ramna",
      "Rampura",
      "Rupnagar",
      "Sabujbagh",
      "Shah Ali",
      "Shahbagh",
      "Shyampur",
      "Sher-e-Bangla Nagar",
      "Sutrapur",
      "Tejgaon",
      "Turag",
      "Vatara",
      "Wari",
    ],
    "Other Dhaka Districts": ["Dohar", "Keraniganj Model", "Keraniganj South", "Nawabganj", "Savar"],
    Gazipur: ["Gazipur Sadar", "Kaliakair", "Kaliganj", "Kapasia", "Sreepur", "Tongi East", "Tongi West"],
    Gopalganj: ["Gopalganj Sadar", "Kashiani", "Kotalipara", "Muksudpur", "Tungipara"],
    Kishoreganj: [
      "Kishoreganj Sadar",
      "Austagram",
      "Bajitpur",
      "Bhairab",
      "Hossainpur",
      "Itna",
      "Karimganj",
      "Katiadi",
      "Kuliarchar",
      "Mithamain",
      "Nikli",
      "Pakundia",
      "Tarail",
    ],
    Madaripur: ["Madaripur Sadar", "Kalkini", "Rajoir", "Shibchar"],
    Manikganj: ["Manikganj Sadar", "Daulatpur", "Ghior", "Harirampur", "Saturia", "Shibalaya", "Singair"],
    Munshiganj: ["Munshiganj Sadar", "Gazaria", "Lauhajang", "Sirajdikhan", "Sreenagar", "Tongibari"],
    Narayanganj: ["Narayanganj Sadar", "Araihazar", "Bandar", "Fatullah", "Rupganj Model", "Siddhirganj", "Sonargaon"],
    Narsingdi: ["Narsingdi Sadar", "Belabo", "Manohardi", "Palash", "Raipura", "Shibpur"],
    Rajbari: ["Rajbari Sadar", "Baliakandi", "Goalanda", "Pangsha", "Kalukhali"],
    Shariatpur: ["Shariatpur Sadar", "Bhedarganj", "Damudya", "Gosairhat", "Naria", "Zajira"],
    Tangail: [
      "Tangail Sadar",
      "Basail",
      "Bhuapur",
      "Delduar",
      "Dhanbari",
      "Ghatail",
      "Gopalpur",
      "Kalihati",
      "Madhupur",
      "Mirzapur",
      "Nagarpur",
      "Sakhipur",
    ],
  },
  "Chittagong Division": {
    "Chittagong Metropolitan": [
      "Akbarshah",
      "Bakolia",
      "Bandar",
      "Bayezid Bostami",
      "Chandgaon",
      "Chattogram Kotwali",
      "Double Mooring",
      "EPZ",
      "Halishahar",
      "Karnaphuli",
      "Khulshi",
      "Kotwali",
      "Pahartali",
      "Panchlaish",
      "Patenga",
      "Sadarghat",
    ],
    "Other Chittagong": [
      "Anwara",
      "Banshkhali",
      "Boalkhali",
      "Chandanaish",
      "Fatikchhari",
      "Hathazari",
      "Lohagara",
      "Mirsharai",
      "Patiya",
      "Rangunia",
      "Raozan",
      "Sandwip",
      "Satkania",
      "Sitakunda",
    ],
    Brahmanbaria: [
      "Brahmanbaria Sadar",
      "Akhaura",
      "Ashuganj",
      "Bancharampur",
      "Bijoynagar",
      "Kasba",
      "Nabinagar",
      "Nasirnagar",
      "Sarail",
    ],
    Chandpur: [
      "Chandpur Sadar",
      "Faridganj",
      "Haimchar",
      "Hajiganj",
      "Kachua",
      "Matlab North",
      "Matlab South",
      "Shahrasti",
    ],
    Comilla: [
      "Comilla Sadar South",
      "Adarsha Sadar",
      "Barura",
      "Brahmanpara",
      "Burichang",
      "Chandina",
      "Chauddagram",
      "Daudkandi",
      "Debidwar",
      "Homna",
      "Laksam",
      "Manoharganj",
      "Meghna",
      "Muradnagar",
      "Nangalkot",
      "Titas",
    ],
    "Cox's Bazar": ["Cox's Bazar Sadar", "Chakaria", "Kutubdia", "Maheshkhali", "Pekua", "Ramu", "Teknaf", "Ukhiya"],
    Feni: ["Feni Sadar", "Chhagalnaiya", "Daganbhuiyan", "Fulgazi", "Parshuram", "Sonagazi"],
    Lakshmipur: ["Lakshmipur Sadar", "Kamalnagar", "Raipur", "Ramganj", "Ramgati"],
    Noakhali: [
      "Noakhali Sadar",
      "Begumganj",
      "Chatkhil",
      "Companiganj",
      "Hatiya",
      "Kabirhat",
      "Senbagh",
      "Sonaimuri",
      "Subarnachar",
    ],
    Rangamati: [
      "Rangamati Sadar",
      "Baghaichhari",
      "Barkal",
      "Belaichhari",
      "Juraichhari",
      "Kaptai",
      "Kawkhali",
      "Langadu",
      "Naniarchar",
      "Rajasthali",
    ],
    Bandarban: ["Bandarban Sadar", "Alikadam", "Lama", "Naikhongchhari", "Rowangchhari", "Ruma", "Thanchi"],
    Khagrachhari: [
      "Khagrachhari Sadar",
      "Dighinala",
      "Lakshmichhari",
      "Mahalchhari",
      "Manikchhari",
      "Matiranga",
      "Panchhari",
      "Ramgarh",
    ],
  },
  "Rajshahi Division": {
    "Rajshahi Metropolitan": ["Boalia", "Motihar", "Rajpara", "Shah Makhdum"],
    Bogra: [
      "Bogra Sadar",
      "Adamdighi",
      "Dhunat",
      "Dupchanchia",
      "Gabtali",
      "Kahalu",
      "Nandigram",
      "Sariakandi",
      "Shahjahanpur",
      "Sherpur",
      "Shibganj",
      "Sonatola",
    ],
    Joypurhat: ["Joypurhat Sadar", "Akkelpur", "Kalai", "Khetlal", "Panchbibi"],
    Naogaon: [
      "Naogaon Sadar",
      "Atrai",
      "Badalgachhi",
      "Dhamoirhat",
      "Manda",
      "Mohadevpur",
      "Niamatpur",
      "Patnitala",
      "Porsha",
      "Raninagar",
      "Sapahar",
    ],
    Natore: ["Natore Sadar", "Bagatipara", "Baraigram", "Gurudaspur", "Lalpur", "Singra"],
    Chapainawabganj: ["Chapainawabganj Sadar", "Bholahat", "Gomastapur", "Nachole", "Shibganj"],
    Pabna: ["Pabna Sadar", "Atgharia", "Bera", "Bhangura", "Chatmohar", "Faridpur", "Ishwardi", "Santhia", "Sujanagar"],
    Sirajganj: [
      "Sirajganj Sadar",
      "Belkuchi",
      "Chauhali",
      "Kamarkhand",
      "Kazipur",
      "Raiganj",
      "Shahjadpur",
      "Tarash",
      "Ullapara",
    ],
  },
  "Khulna Division": {
    "Khulna Metropolitan": [
      "Khulna Kotwali",
      "Sonadanga",
      "Khalishpur",
      "Daulatpur",
      "Khan Jahan Ali",
      "Aranghata",
      "Labanchara",
      "Harintana",
    ],
    Bagerhat: [
      "Bagerhat Sadar",
      "Chitalmari",
      "Fakirhat",
      "Kachua",
      "Mollahat",
      "Mongla",
      "Morrelganj",
      "Rampal",
      "Sarankhola",
    ],
    Jessore: [
      "Jessore Kotwali",
      "Abhaynagar",
      "Bagherpara",
      "Chaugachha",
      "Jhikargachha",
      "Keshabpur",
      "Manirampur",
      "Sharsha",
    ],
    Jhalokathi: ["Jhalokathi Sadar", "Kathalia", "Nalchity", "Rajapur"],
    Jhenaidah: ["Jhenaidah Sadar", "Harinakunda", "Kaliganj", "Kotchandpur", "Maheshpur", "Shailkupa"],
    Kushtia: ["Kushtia Sadar", "Bheramara", "Daulatpur", "Kumarkhali", "Khoksa", "Mirpur"],
    Magura: ["Magura Sadar", "Mohammadpur", "Shalikha", "Sreepur"],
    Meherpur: ["Meherpur Sadar", "Gangni", "Mujibnagar"],
    Narail: ["Narail Sadar", "Kalia", "Lohagara"],
    Satkhira: ["Satkhira Sadar", "Assasuni", "Debhata", "Kalaroa", "Kaliganj", "Shyamnagar", "Tala"],
  },
  "Barisal Division": {
    "Barisal Metropolitan": ["Kotwali Model", "Airport", "Bandar", "Kaunia"],
    "Barisal District": [
      "Agailjhara",
      "Babuganj",
      "Bakerganj",
      "Banaripara",
      "Gaurnadi",
      "Hizla",
      "Mehendiganj",
      "Muladi",
      "Uzirpur",
    ],
    Bhola: ["Bhola Sadar", "Burhanuddin", "Char Fasson", "Daulat Khan", "Lalmohan", "Manpura", "Tazumuddin"],
    Barguna: ["Barguna Sadar", "Amtali", "Bamna", "Betagi", "Patharghata", "Taltali"],
    Patuakhali: ["Patuakhali Sadar", "Bauphal", "Dashmina", "Dumki", "Galachipa", "Kalapara", "Mirzaganj", "Rangabali"],
    Pirojpur: ["Pirojpur Sadar", "Bhandaria", "Kawkhali", "Mathbaria", "Nesarabad", "Nazirpur", "Zianagar"],
  },
  "Sylhet Division": {
    "Sylhet Metropolitan": ["Kotwali Model", "Airport", "Dakshin Surma", "Moglabazar", "Shahporan", "Jalalabad"],
    "Sylhet District": [
      "Balaganj",
      "Beanibazar",
      "Bishwanath",
      "Companiganj",
      "Fenchuganj",
      "Golapganj",
      "Gowainghat",
      "Jaintiapur",
      "Kanaighat",
      "Osmaninagar",
      "Zakiganj",
    ],
    Habiganj: [
      "Habiganj Sadar",
      "Ajmiriganj",
      "Bahubal",
      "Baniachong",
      "Chunarughat",
      "Lakhai",
      "Madhabpur",
      "Nabiganj",
    ],
    Moulvibazar: ["Moulvibazar Sadar", "Barlekha", "Juri", "Kamalganj", "Kulaura", "Rajnagar", "Sreemangal"],
    Sunamganj: [
      "Sunamganj Sadar",
      "Bishwambarpur",
      "Chhatak",
      "Derai",
      "Dharmapasha",
      "Dowarabazar",
      "Jagannathpur",
      "Jamalganj",
      "Sulla",
      "Tahirpur",
    ],
  },
  "Rangpur Division": {
    "Rangpur Metropolitan": [
      "Kotwali",
      "Tajhat",
      "Haragach",
      "Gangachara",
      "Mithapukur",
      "Pirgachha",
      "Badarganj",
      "Taraganj",
    ],
    Dinajpur: [
      "Dinajpur Sadar",
      "Birampur",
      "Birganj",
      "Biral",
      "Bochaganj",
      "Chirirbandar",
      "Fulbari",
      "Ghoraghat",
      "Hakimpur",
      "Kaharole",
      "Khansama",
      "Nawabganj",
      "Parbatipur",
    ],
    Gaibandha: ["Gaibandha Sadar", "Fulchhari", "Gobindaganj", "Palashbari", "Sadullapur", "Saghata", "Sundarganj"],
    Kurigram: [
      "Kurigram Sadar",
      "Bhurungamari",
      "Char Rajibpur",
      "Chilmari",
      "Nageshwari",
      "Phulbari",
      "Rajarhat",
      "Raumari",
      "Ulipur",
    ],
    Lalmonirhat: ["Lalmonirhat Sadar", "Aditmari", "Hatibandha", "Kaliganj", "Patgram"],
    Nilphamari: ["Nilphamari Sadar", "Dimla", "Domar", "Jaldhaka", "Kishoreganj", "Saidpur"],
    Panchagarh: ["Panchagarh Sadar", "Atwari", "Boda", "Debiganj", "Tetulia"],
    Thakurgaon: ["Thakurgaon Sadar", "Baliadangi", "Haripur", "Pirganj", "Ranisankail"],
  },
  "Mymensingh Division": {
    Mymensingh: [
      "Mymensingh Sadar",
      "Bhaluka",
      "Dhobaura",
      "Fulbaria",
      "Gafargaon",
      "Gouripur",
      "Haluaghat",
      "Ishwarganj",
      "Muktagachha",
      "Nandail",
      "Phulpur",
      "Trishal",
    ],
    Jamalpur: ["Jamalpur Sadar", "Bakshiganj", "Dewanganj", "Islampur", "Madarganj", "Melandaha", "Sarishabari"],
    Netrokona: [
      "Netrokona Sadar",
      "Atpara",
      "Barhatta",
      "Durgapur",
      "Kendua",
      "Khaliajuri",
      "Kalmakanda",
      "Madan",
      "Mohanganj",
      "Purbadhala",
    ],
    Sherpur: ["Sherpur Sadar", "Jhenaigati", "Nakla", "Nalitabari", "Sreebardi"],
  },
}

// Helper function to get flat list of all thanas with hierarchy info
export interface ThanaOption {
  value: string
  label: string
  division: string
  district: string
  thana: string
}

export function getAllThanas(): ThanaOption[] {
  const thanas: ThanaOption[] = []

  for (const [division, districts] of Object.entries(bangladeshThanas)) {
    for (const [district, thanaList] of Object.entries(districts)) {
      for (const thana of thanaList) {
        thanas.push({
          value: `${thana} PS, ${district}`,
          label: `${thana} PS`,
          division,
          district,
          thana,
        })
      }
    }
  }

  return thanas.sort((a, b) => a.thana.localeCompare(b.thana))
}

// Get total count of thanas
export function getTotalThanaCount(): number {
  let count = 0
  for (const districts of Object.values(bangladeshThanas)) {
    for (const thanaList of Object.values(districts)) {
      count += thanaList.length
    }
  }
  return count
}
